// Imediately Invoked Fuction Expression (IIFE)
// to remove the pollution generated by global variables or declarations

(function chai(){
    //Named IIFE
    console.log(`DB CONNECTED`);
})();

( (name) => {
    // simple IIFE
    console.log(`DB CONNECTED TWO ${name}`);
})("Vishal");
